import { ShieldCheck, Anchor, Package, Building2, Lock, Zap } from 'lucide-react';

export const certifications = [
  {
    id: 'iso-9001',
    name: 'ISO 9001:2015',
    category: 'Quality Management',
    icon: <ShieldCheck className="h-8 w-8" />,
    issuer: 'International Organization for Standardization (ISO)',
    scope: 'Quality Management System for terminal operations and customs services',
    validFrom: '2022-03-15',
    validUntil: '2025-03-14',
    status: 'Active',
    description: 'Demonstrates commitment to consistent quality in all terminal services and customer satisfaction.',
  },
  {
    id: 'iso-14001',
    name: 'ISO 14001:2015',
    category: 'Environmental Management',
    icon: <ShieldCheck className="h-8 w-8" />,
    issuer: 'International Organization for Standardization (ISO)',
    scope: 'Environmental Management System including waste management and emissions control',
    validFrom: '2022-05-20',
    validUntil: '2025-05-19',
    status: 'Active',
    description: 'Ensures environmentally responsible operations with systematic environmental impact management.',
  },
  {
    id: 'iso-45001',
    name: 'ISO 45001:2018',
    category: 'Occupational Health & Safety',
    icon: <ShieldCheck className="h-8 w-8" />,
    issuer: 'International Organization for Standardization (ISO)',
    scope: 'Occupational Health and Safety Management System',
    validFrom: '2023-01-10',
    validUntil: '2026-01-09',
    status: 'Active',
    description: 'Maintains the highest workplace safety standards with comprehensive hazard management.',
  },
  {
    id: 'solas',
    name: 'SOLAS Compliance',
    category: 'Maritime Safety',
    icon: <Anchor className="h-8 w-8" />,
    issuer: 'International Maritime Organization (IMO)',
    scope: 'Safety of Life at Sea - Port facility security and vessel operations',
    validFrom: '2020-01-01',
    validUntil: '2026-12-31',
    status: 'Active',
    description: 'Full compliance with Safety of Life at Sea regulations for international maritime operations.',
  },
  {
    id: 'imdg',
    name: 'IMDG Code Certification',
    category: 'Dangerous Goods Handling',
    icon: <Package className="h-8 w-8" />,
    issuer: 'International Maritime Organization (IMO)',
    scope: 'International Maritime Dangerous Goods Code - Hazmat handling and storage',
    validFrom: '2021-06-15',
    validUntil: '2024-12-31',
    status: 'Active',
    description: 'Authorized to handle, store, and transport dangerous goods with full IMO compliance.',
  },
  {
    id: 'ism-code',
    name: 'ISM Code Compliance',
    category: 'Maritime Safety Management',
    icon: <Anchor className="h-8 w-8" />,
    issuer: 'International Maritime Organization (IMO)',
    scope: 'International Safety Management Code for port facility operations',
    validFrom: '2020-06-01',
    validUntil: '2025-12-31',
    status: 'Active',
    description: 'Comprehensive safety management system for maritime terminal operations.',
  },
  {
    id: 'isps-code',
    name: 'ISPS Code Certification',
    category: 'Port Security',
    icon: <Lock className="h-8 w-8" />,
    issuer: 'International Maritime Organization (IMO)',
    scope: 'International Ship and Port Facility Security Code',
    validFrom: '2020-03-20',
    validUntil: '2025-12-31',
    status: 'Active',
    description: 'Enhanced security measures for vessels and cargo with international port standards.',
  },
  {
    id: 'aeo',
    name: 'Authorized Economic Operator (AEO)',
    category: 'Customs Compliance',
    icon: <Building2 className="h-8 w-8" />,
    issuer: 'World Customs Organization (WCO)',
    scope: 'AEO certification - customs compliance and supply chain security',
    validFrom: '2022-09-01',
    validUntil: '2025-08-31',
    status: 'Active',
    description: 'Authorized to expedite customs procedures with reduced inspection rates.',
  },
  {
    id: 'ctpat',
    name: 'CTPAT Participation',
    category: 'Trade Security',
    icon: <Lock className="h-8 w-8" />,
    issuer: 'U.S. Customs and Border Protection (CBP)',
    scope: 'Customs-Trade Partnership Against Terrorism - Supply chain security',
    validFrom: '2021-04-15',
    validUntil: '2024-04-14',
    status: 'Active',
    description: 'Partnership with U.S. CBP for enhanced security and expedited trade benefits.',
  },
  {
    id: 'csi',
    name: 'Container Security Initiative (CSI)',
    category: 'Container Security',
    icon: <Zap className="h-8 w-8" />,
    issuer: 'U.S. Customs and Border Protection (CBP)',
    scope: 'CSI port participation for container screening and verification',
    validFrom: '2019-01-01',
    validUntil: '2026-12-31',
    status: 'Active',
    description: 'Advanced container screening and security protocols at participating ports.',
  },
  {
    id: 'licensed-broker',
    name: 'Licensed Customs Broker',
    category: 'Customs Authority',
    icon: <Building2 className="h-8 w-8" />,
    issuer: 'National Customs Authority',
    scope: 'Official customs brokerage license for import/export clearance',
    validFrom: '2020-12-01',
    validUntil: '2025-11-30',
    status: 'Active',
    description: 'Authorized customs broker for all import/export and customs clearance services.',
  },
  {
    id: 'port-authority',
    name: 'Port Terminal Operator License',
    category: 'Port Authority',
    icon: <Anchor className="h-8 w-8" />,
    issuer: 'Port Authority',
    scope: 'Terminal operator license for bonded warehouse and CFS operations',
    validFrom: '2021-07-15',
    validUntil: '2026-07-14',
    status: 'Active',
    description: 'Full authorization for terminal operations including bonded facilities.',
  },
];

export const certificationCategories = {
  safety: 'Maritime Safety',
  quality: 'Quality Management',
  environmental: 'Environmental Management',
  health: 'Occupational Health & Safety',
  customs: 'Customs & Trade',
  security: 'Security & Port Facility',
};
